server:
  port: 8082
databases:
  - user: admin
    password: admin
    host: localhost
    dbName: shopDev
  - user: admin
    password: admin
    host: localhost
    dbName: shopDev
security:
  jwt:
    key: abc123
